[package]
name = "qudp"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true }
socket2 = { workspace = true }
libc = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
